// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Member struct {
	ID    string   `json:"id"`
	Name  string   `json:"name"`
	Age   string   `json:"age"`
	Skill []*Skill `json:"skill"`
}

type MemberSkill struct {
	ID       string `json:"id"`
	MemberID string `json:"memberID"`
	SkillID  string `json:"skillID"`
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewMember struct {
	Name     string   `json:"name"`
	Age      string   `json:"age"`
	SkillIDs []string `json:"skillIDs"`
}

type NewMemberSkill struct {
	MemberID string `json:"memberID"`
	SkillID  string `json:"skillID"`
}

type NewSkill struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Skill struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
